<a href="https://colab.research.google.com/github/sunitadhotre/Artificial-Intelligence/blob/main/Day6_Assignment_SSD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
ta = tf.constant(49)
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [3]:
ta.shape

TensorShape([])

In [4]:
ta.dtype

tf.int32

In [5]:
tb = tf.constant([[2.,5.],[9.,4.]])
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [6]:
tb.shape

TensorShape([2, 2])

In [7]:
tb.dtype

tf.float32

Subsetting tensor

In [8]:
tb[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 4.], dtype=float32)>

In [ ]:
tb[0,:]

In [9]:
ta+4

<tf.Tensor: shape=(), dtype=int32, numpy=53>

Mathematical Operations

In [10]:
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [11]:
tf.transpose(tb)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 9.],
       [5., 4.]], dtype=float32)>

In [ ]:
Matrix Multiplication

In [12]:
tc = tf.constant([[3.,4.],[7.,9.],[0.,2.]])
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>

In [13]:
tc @ tb

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[42., 31.],
       [95., 71.],
       [18.,  8.]], dtype=float32)>

Calculations

In [ ]:
tf.reduce_sum(tc)

In [ ]:
tf.reduce_mean(tc)

In [14]:
tf.reduce_max(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [15]:
tf.math.log(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.0986123, 1.3862944],
       [1.9459101, 2.1972246],
       [     -inf, 0.6931472]], dtype=float32)>

In [16]:
tf.math.exp(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.0085537e+01, 5.4598148e+01],
       [1.0966332e+03, 8.1030840e+03],
       [1.0000000e+00, 7.3890562e+00]], dtype=float32)>

Type Conversions

In [17]:
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [18]:
td = tf.constant(57.)

In [19]:
ta + td

InvalidArgumentError: ignored

In [20]:
td +  tf.cast(ta, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=106.0>

tf.Variable()
Variables created in this way, are mutable and can be used to implement weights in neural networks

In [22]:
va = tf.Variable([[22.,35.,59.],[45.,98.,23.]])
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[22., 35., 59.],
       [45., 98., 23.]], dtype=float32)>

In [23]:
va.assign(3*va)
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 66., 105., 177.],
       [135., 294.,  69.]], dtype=float32)>

Trying it with constant tensor

In [24]:
tc = tf.constant([[3.,4.],[7.,9.],[0.,2.]])
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>